FROM php:5.6-apache
RUN docker-php-ext-install mysql mysqli pdo pdo_mysql
COPY src/ /var/www/html/

#docker build -f Dockerfile-php -t bradeac/php .

#docker run --name php --link db:mysql -p 41062:80 -d bradeac/php

