version: "2"
services:
  mysql:
    image: bradeac/mysql
    container_name: mysql
    ports:
     - "3306:3306"
    volumes_from:
     - data
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: PROIECT
  php:
    image: bradeac/php
    ports:
     - "41062:80"
  data:
    image: bradeac/data
    container_name: data
