FROM mysql:5.7

EXPOSE 3306
#docker build -f Dockerfile-db -t bradeac/db .

#docker run --name mysql -e MYSQL_ROOT_PASSWORD=password -d bradeac/mysql

#docker run -it --link mysql:mysql --rm mariadb sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -ppassword'

#mysql -proot PROIECT < tmp/sql/proiect.sql

