FROM mysql


#docker build -f Dockerfile-db -t bradeac/db .

#docker run --name db -e MYSQL_ROOT_PASSWORD=rs6avant -d bradeac/db

#docker run -it --link db:mysql --rm mariadb sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -prs6avant'


#mysql -proot PROIECT < tmp/sql/proiect.sql

